---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-flask-web
  name: my-flask-web
spec:
  containers:
  - image: flask_web:v1
    name: my-flask-web
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
