---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-flask-web
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: my-flask-web
status:
  loadBalancer: {}

